### ISSUE TITLE
Could not find the End of Central Directory Record

### ISSUE THREAD

**Issue by richacker** [mllrsohn/node-webkit-builder#132]
C:\Users\paxcel\Desktop\grunt>nwbuild -r C:\Users\paxcel\Desktop\nodebob\app
Latest Version: v0.11.2
Using v0.11.2
Create cache folder in C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\cache\0.11.2
Downloading: http://dl.node-webkit.org/v0.11.2/node-webkit-v0.11.2-win-ia32.zip
Possibly unhandled Error: Could not find the End of Central Directory Record
at DecompressZip.findEndOfDirectory (C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\lib\decompress-zip.js:168:15)
at _fulfilled (C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\node_modules\q\q.js:787:54) 
at self.promiseDispatch.done (C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\node_modules\q\q.js:816:30) 
at Promise.promise.promiseDispatch (C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\node_modules\q\q.js:749:13)
at C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\node_modules\q\q.js:557:44
at flush (C:\Users\paxcel\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\decompress-zip\node_modules\q\q.js:108:17) at process._tickCallback (node.js:419:13)

**Comment by cnsharp** [comment]
I also encount the same error,it must be downloading disconnected.I'm sure about that because I'm in a isolated country.Is there any way to put it in a specific directory,so I can download it manually by special tools?

**Comment by DblK** [comment]
If you want to download it manually you can do it.
Simply go to http://dl.nwjs.io/v0.15.4/ download all those files :
* nwjs-sdk-v0.15.4-linux-ia32.tar.gz
* nwjs-sdk-v0.15.4-linux-x64.tar.gz
* nwjs-sdk-v0.15.4-osx-x64.zip
* nwjs-sdk-v0.15.4-win-ia32.zip
* nwjs-sdk-v0.15.4-win-x64.zip

Extract files in each directy by platform and put them in the cache folder of the root directory of your application.
You should have a tree like that

```
cache
│
└───0.15.4
      └───win32
      └───win64
      └───osx32
	  └───osx64
      └───linux32
	  └───linux64
